### ISSUE TITLE
Analysis Results

### ISSUE THREAD

**Issue by konvoulgaris** [DIASTEMA-UPRC/analytics-catalogue#1]
Για το συγκεκριμένο task Θα πρέπει να συγκεντρωθούν μια σειρά απο μετρικές και γραφήματα τα οποία είναι κατάλληλα για την αποτίμηση των εφαρμογών που προσφέρονται από το Diastema. Αυτά μετέπειτα θα δίνονται ως είσοδος στο UI για την αξιολόγηση της ανάλυσης. 

ΠΧ 
1. Classification : F1, accuracy , ROC, confusion matrix , etc 
2. Regression : R2 , RMSE etc 
3. Neural Network Specifics : Training -Test Loss / Acc 
4. ......

**Comment by konvoulgaris** [comment]
@karamolegkos discussion whenever you can for this. send me pm

**Comment by konvoulgaris** [comment]
Planning on doing this by passing a firth argument with the spark-job. Meaning the command will now be:

`spark-submit --conf spark.executorEnv.MINIO_HOST="analytics-catalogue-minio" src/ClassificationJob.py decisiontree test/in test/out quality 1`

where the last argument, in example "1", is the job-id (is string, happened to be 1)

The Spark Job will then connect to the mongoDB and export the following results based on the Job-ID on the "Analytics" collection

![image](https://user-images.githubusercontent.com/36533602/187041458-408e607d-b26e-4312-a462-984ebcd184d5.png)

**Comment by konvoulgaris** [comment]
please input @karamolegkos

**Comment by konvoulgaris** [comment]
After a thorough and extensive discussion with @karamolegkos we have concluded that the command call for the Spark Job should abide by the following call schema:

`spark-submit --conf spark.executorEnv.ENV="x" <Job>.py <algorithm> <input_path> <output_path> <target_column> <job_id> <analysis_id>`

Furthermore, both the job_id and anaysis_id should be exported to the mongo collection

**Comment by karamolegkos** [comment]
Μετά από συζήτηση θα γίνει και προσθήκη της πληροφορίας Host και Port της Mongo DB ώστε να μπορεί να γίνει πιο ευέλικτο το παραπάνω σύστημα στο deployment phase.

**Comment by konvoulgaris** [comment]
Implementation is merged, please check orchestration harmony @karamolegkos 

Example command:

```
spark-submit \
--conf spark.executorEnv.MINIO_HOST="127.0.0.1" \
--conf spark.executorEnv.MINIO_PORT="9000" \
--conf spark.executorEnv.MINIO_USER="diastema" \
--conf spark.executorEnv.MINIO_PASS="diastema" \ 
--conf spark.executorEnv.MONGO_HOST="127.0.0.1" \
--conf spark.executorEnv.MONGO_PORT="27017" \
src/ClassificationJob.py decisiontree test/in test/out quality 1
```

Remember the job_id at the end (in example "1")!!

**Comment by konvoulgaris** [comment]
forgot to mention that the new docker image is also up. so that's that 😊

**Comment by karamolegkos** [comment]
Got it @konvoulgaris !
Soon I will do the appropriate updates in the Orchestration as well to move this issue as ready.

**Comment by karamolegkos** [comment]
Made the updates in the Orchestrator. Tested them as well. Moving issue in the integration phase.

**Comment by karamolegkos** [comment]
✔️ Οι αλλαγές αυτού του issue έχουν γίνει integrated στο Diastema Cloud.
Δεν το μετακινώ για να μετακινηθεί στο επόμενο meeting από τον @yannispoulakis .
