### ISSUE TITLE
Clustering Algorithms

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/analytics-catalogue#3]
Inclusion of some clustering algorithms in our data-services to complete the family of the major machine learning tasks.

**Comment by karamolegkos** [comment]
The team started implimenting the clustering algorithms.
Steps TODO:
- [x] Add a clustering node with its algorithms in the Web Application.
- [x] Make the new Algorithms.
- [x] Make the new updates for the Orchestration based on the above.

**Comment by konvoulgaris** [comment]
Test with KMeans for now. Thanks 😊

**Comment by adreaskar** [comment]
Clustering Node has been added to Process Modelling

Περιμένω Input για το τι αλγορίθμους θα χρησιμοποιεί

**Comment by karamolegkos** [comment]
Αφήνω παρακάτω τα αναγκαία στοιχεία. Ότι άλλο χρειαστείς μου λες @adreaskar 
- Job title: "clustering"
- Algorithms allowed: Only "k-means clustering" for now.

**Comment by karamolegkos** [comment]
Orchestration Updates are done.

**Comment by karamolegkos** [comment]
The K-means algorithm of the Spark Image is working @konvoulgaris . It is tested by me.
