### ISSUE TITLE
Saved model execution

### ISSUE THREAD

**Issue by konvoulgaris** [DIASTEMA-UPRC/analytics-catalogue#5]
We need to have a way to save and run models later

**Comment by konvoulgaris** [comment]
Models will be executed on a new service called daas-analytics-catalogue-executor

The orchestrator will need to follow the following logic:

GET /health 
Once this is 200 the service has started

POST /start/<job_id>
Load the model with the job_id used in the analytics_catalogue step, it has to be the same. 
POST /predict
This will accept raw data and predict it. You have to include the column names in the first line. Also must follow the format of the csv. For example:

prediction request raw data expected:
```
x, y
-1.42811500584555, 3.76194843454781
-0.0937990215106019, 3.40634508630138
 0.149619792650416,  2.84290718332174
```

In the above example the executor will predict using the model for 3 samples

**Comment by konvoulgaris** [comment]
The executor is as separate service so that the orchestrator can adjust its running parameter to achieve "targeted scalability". This can be achieved by the following config on spark-submit

```
--conf spark.executor.instances="10"
--conf spark.executor.memory="4g"
--conf spark.executor.cores="2"
```

All values must be strings and do the adjust the execution of the executor


Also since this is now an API you can/must also set the following conf parameters:
```
--conf spark.executorEnv.FLASK_HOST="0.0.0.0"
--conf spark.executorEnv.FLASK_HOST="5000"
--conf spark.executorEnv.FLASK_HOST="True"
```

**Comment by konvoulgaris** [comment]
Also the orchestrator **MUST CREATE A BUCKET NAMED "diastemamodels" BEFORE** running any analytics-catalogue job

**Comment by konvoulgaris** [comment]
@karamolegkos 

not available for call until monday, communication via text until then is however possible

**Comment by karamolegkos** [comment]
Περιμένω για να  κάνουμε το internal UPRC meeting μας για να ολοκληρώσουμε τα σχετικά μας guides για τις νέες αλλαγές.
Αυτή η αναμονή θα γίνει έχοντας υπόψη τον τρόπο με τον οποίο τα νέα inputs θα έρχονται από το Web Application στον Orchestrator και στην συνέχεια θα προωθούνται στα services που αναφέρονται παραπάνω.

**Comment by konvoulgaris** [comment]
Final updates following specification updates before intergration. @karamolegkos 

## Running the job
MongoDB connnection metadata is now **REQUIRED**. Please take note of the following command below to see all available env vars. I have included the default values as the initial input, please change them accordingly

Example command
```
spark-submit \
--conf spark.executorEnv.FLASK_HOST="localhost" \
--conf spark.executorEnv.FLASK_PORT="5000" \
--conf spark.executorEnv.MINIO_HOST="localhost" \
--conf spark.executorEnv.MINIO_PORT="9000" \
--conf spark.executorEnv.MINIO_USER="minioadmin" \
--conf spark.executorEnv.MINIO_PASS="minioadmin" \
--conf spark.executorEnv.MONGO_HOST="localhost" \
--conf spark.executorEnv.MONGO_PORT="27017" \
src/main.py
```

## Notes
When calling /stop the returning value is not guaranteed. If the request is dropped or responds normally, you should consider the job to be now stopped/killed.

Following discussion on technical meeting, columns names on /predict are not required. The request only needs to include the samples now. For example now it is:

```
8.42954405116883,10.3104502614474
8.48126384793122,10.6044070049211
8.83738509966331,10.6722477165529
8.89821530147121,10.787268851993
```

Instead of 

```
x,y
8.42954405116883,10.3104502614474
8.48126384793122,10.6044070049211
8.83738509966331,10.6722477165529
8.89821530147121,10.787268851993
```

**Comment by karamolegkos** [comment]
Moved in Integration to be tested with the Runtime Manager.

**Comment by karamolegkos** [comment]
@konvoulgaris 
Found a bug, check slack to fix.

**Comment by karamolegkos** [comment]
Integrated.
--> Tested and working as expected.
